services:
  - type: web
    name: steengroeve-website
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn website_app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    autoDeployTrigger: commit
